// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_movies from "./routes/api/movies.ts";
import * as $api_movies_id_ from "./routes/api/movies/[id].ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $MovieForm from "./islands/MovieForm.tsx";
import * as $MovieList from "./islands/MovieList.tsx";
import * as $Todos from "./islands/Todos.tsx";
import * as $clientes from "./islands/clientes.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/movies.ts": $api_movies,
    "./routes/api/movies/[id].ts": $api_movies_id_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/MovieForm.tsx": $MovieForm,
    "./islands/MovieList.tsx": $MovieList,
    "./islands/Todos.tsx": $Todos,
    "./islands/clientes.tsx": $clientes,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
